vich_uploader:
    db_driver: orm
    mappings:
        product_model_images:
            uri_prefix: '%app.path.product_model_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/product_models'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        shape_images:
            uri_prefix: '%app.path.shape_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/shapes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        product_images:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/product_images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        product_overview_images:
            uri_prefix: '%app.path.product_overview_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        product_variant_images:
            uri_prefix: '%app.path.product_variant_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/product_variant_images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        category_images:
            uri_prefix: /uploads/images/categories
            upload_destination: '%kernel.project_dir%/public/uploads/images/categories'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        color_images:
            upload_destination: '%kernel.project_dir%/public/uploads/images/colors'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        offer_images:
            uri_prefix: /uploads/offers
            upload_destination: '%kernel.project_dir%/public/uploads/offers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        product_overlay_files:
            uri_prefix: /uploads/overlays/products
            upload_destination: '%kernel.project_dir%/public/uploads/overlays/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        product_variant_overlay_files:
            uri_prefix: /uploads/overlays/variants
            upload_destination: '%kernel.project_dir%/public/uploads/overlays/variants'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true